---
title: "p8105_hw2_ht2607"
output: github_document
---

## Question 1

```{r setup, include=FALSE}
library(tidyverse)
library(tidyr)
```

```{r}
pols_month_df = read_csv(file = "./fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names(pols_month_df) |>
  pols_month_df <- pols_month_df %>%
  separate(mon, into = c("year", "month", "day"), sep = "-")

```

## Question 2

```{r}
library(readxl)
library(tidyverse)
mr_trash_df = read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30)
```

```{r}
professor_trash_df = read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30)
```

```{r}
gwynnda_df= read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel") |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(homes_powered = weight_tons*500/30)
```

```{r}
mr_trash_df = 
  readxl::read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel") |>
  mutate(trash_wheel = "mr.trash")

professor_trash_df = 
  readxl::read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel") |>
  mutate(trash_wheel = "professor trash")

gwynnda_df = 
  readxl::read_excel("q2data/202207 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel") |>
  mutate(trash_wheel = "gwynnda")

trash_df_tidy = 
  bind_rows(mr_trash_df, professor_trash_df, gwynnda_df) |>
  janitor::clean_names()
```

